### ISSUE TITLE
Update to Influxdb v2

### ISSUE THREAD

**Issue by tzockt** [wopfel/sbfspot2influxdb#1]
Hello,

can you update your Script to Influxdb v2?

Thx!

TZockt

**Comment by wopfel** [comment]
Hello @tzockt,

Thanks for opening this issue. I'm glad I've migrated my InfluxDB from v1 to v2 some days ago. So I can share the changed script quickly now.

Hopefully the script is well enough documented - at least for the bucket name etc. 😊 Have a look at the `$curlcall` definition.

Thank you for your interest in this repository. I was unsure if anyone will ever find it useful.
Feedback is welcome!

Kind regards,
Bernd
